Repository loafoe/mattermost-client, pull requests merged in 2019-10, with the labels that each got.

#98 Setup GitHub Actions - closes #59
  .github/workflows/main.yml
Labels: build

#102 Run GitHub Actions for pull requests
  .github/workflows/main.yml
Labels: build

#101 Add the GitHub Actions status badge
  README.md
Labels: docs

#100 Set job name
  .github/workflows/main.yml
Labels: build

#107 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest
